Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:BaseMigration...
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:CanBeV1Migrated...
Vulnerability: Reentrancy. Maybe in function: 0x51eb3412. PC: 0x273. Line number: 366.
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:ICards...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:IERC165...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:IERC721...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:IPackFour...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0x5f38c57b268664015de387229bc9d3822b53ec32.sol:v1Migration...

--- STDERR ---
PHI instruction need arguments but 0 was given

Traceback (most recent call last):
  File "/home/sh1kaku/lihao/conkas/conkas.py", line 108, in main
    traces = sym_exec.execute()
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/instructions/rattle_instructions.py", line 58, in inst_phi
    raise Exception
Exception
