Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0xb588530e3956d9787b0429244ca360f566ff3301.sol:BaseUnilotGame...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0xb588530e3956d9787b0429244ca360f566ff3301.sol:Game...
Nothing to analyse
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0xb588530e3956d9787b0429244ca360f566ff3301.sol:TicketLib...
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0xb588530e3956d9787b0429244ca360f566ff3301.sol:UnilotPrizeCalculator...
Analysing ../../SCRUBD/SCRUBD-CD/data/solidity_codes/0xb588530e3956d9787b0429244ca360f566ff3301.sol:UnilotTailEther...
Vulnerability: Reentrancy. Maybe in function: calcaultePrizes(). PC: 0x872. Line number: 318.

--- STDERR ---
PHI instruction need arguments but 0 was given

Traceback (most recent call last):
  File "/home/sh1kaku/lihao/conkas/conkas.py", line 108, in main
    traces = sym_exec.execute()
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 51, in execute
    new_traces = self.__sym_exec_traces(traces_to_execute)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 64, in __sym_exec_traces
    new_blocks = self.__sym_exec_block(block_to_analyse, trace.state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 93, in __sym_exec_block
    new_blocks = self.__sym_exec_instruction(instruction, state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/symbolic_executor.py", line 116, in __sym_exec_instruction
    return func(instruction, state)
  File "/home/sh1kaku/lihao/conkas/sym_exec/instructions/rattle_instructions.py", line 58, in inst_phi
    raise Exception
Exception
